
data:
    #"path/to/data/samples/ given as a folder"
    # if reads are PE then they shouls share the same base_name + "_1"/"_2"
    samples: '/mnt/c/Users/zosia/Desktop/Studia/mgr/ADP/projekt/data_2/'
    #"path/to/data/reference.fa"
    reference: '/mnt/c/Users/zosia/Desktop/Studia/mgr/ADP/projekt/data_2/reference/GCA_000298735.1.fasta.gz'
    # path to file which specifies control group
    # one line = one base_name of file
    control: '/mnt/c/Users/zosia/Desktop/Studia/mgr/ADP/projekt/data_2/control.txt'

settings:
    # Option to check given data using trimmomatic
    # Options: "true", "false"
    trim: "true"
    
    # Select programm used used for read mapping.
    # Options: "hisat", "bwa", "bowtie2"
    mapping: "hisat"
    
    # Reads type:
    # Options: "se", "pe"
    reads: "pe"

    # Option to annotate found variants using vep
    # Options: "true", "false"
    annotate: "true"

    # What type of data was sequenced
    # Options: "rna", "dna"
    type:
        "rna"

    # Option to show used filters by plotting them and saving to file
    # Options: "true", "false"
    visualize_filters:
        "true"



    

params:
    fastqc:
        threads:
            6
    # Used only if trim == true
    # Parameters used while trimming sequencing data
    trimmomatic:
        threads: 6
        se:
            
            - "LEADING:3"
            - "TRAILING:3"
            - "SLIDINGWINDOW:4:15"
            - "MINLEN:36"
        pe:
            - "LEADING:3"
            - "TRAILING:3"
            - "SLIDINGWINDOW:4:15"
            - "MINLEN:36"

    # Parameters used for mapping
    hisat:
        threads: 6

    bwa:
       threads: 6
        
    bowtie2:
        threads: 6

    gatk:
        splitNcigar:
            threads:
                6
        haplotype:
            threads:
                6
        table:
            threads:
                6
        filtering:
            snvs:
                "QD < 5.0 || QUAL < 35.0 || SOR > 2.5 || FS > 50.0 || MQ < 55.0 || MQRankSum < -12.5 || ReadPosRankSum < -8.0 || DP < 10"
            indels:
                "QD < 5.0 || QUAL < 35.0 || FS > 75.0 || ReadPosRankSum < -10.0 || DP < 10.0"

    vep:
        # It is needed to fill some data to run VEP from Ensembl site (https://uswest.ensembl.org/info/docs/tools/vep/script/vep_cache.html)
        data:
            # Ensembl species name
            species:
                "ovis_aries"

            # Should be the same as used vep version 
            release:
                98
            build:
                "R64-1-1"
            
            plugins:
                - LoFtool
        annotate:
            threads: 6
                    
            